[package]
name = "telekey"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
hostname = "0.3.1"
quick-protobuf = "0.8.0"
console = "0.15.2"
queue = "0.3.1"
chrono = { version = "0.4.23", features = ["alloc", "clock", "std", "time"], default-features = false }
